FROM jenkins/jenkins:lts
USER root
# Install Docker CLI + kubectl so Jenkins can build/push images and deploy to K8s
RUN apt-get update && apt-get install -y docker.io curl \
    && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
USER jenkins
